# Generated by Django 3.1.4 on 2021-01-25 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_aboutdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutdata',
            old_name='country',
            new_name='city',
        ),
        migrations.RemoveField(
            model_name='aboutdata',
            name='extraInfobotoom',
        ),
        migrations.AddField(
            model_name='aboutdata',
            name='extraInfobottom',
            field=models.TextField(default='Text', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aboutdata',
            name='firstParagraph',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='aboutdata',
            name='skillText',
            field=models.TextField(max_length=300),
        ),
    ]
