# Generated by Django 3.1.4 on 2021-02-01 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_auto_20210126_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.TextField(max_length=300)),
                ('level', models.CharField(choices=[('Basic', 'Basic'), ('Medium', 'Medium'), ('Advance', 'Advance')], max_length=7)),
            ],
        ),
    ]
