# Generated by Django 3.1.4 on 2021-02-01 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_skilldata_percentaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='skilldata',
            name='img',
            field=models.ImageField(blank=True, upload_to='Images'),
        ),
        migrations.AlterField(
            model_name='skilldata',
            name='skill',
            field=models.CharField(max_length=30),
        ),
    ]
