# Generated by Django 3.1.4 on 2021-02-01 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0009_auto_20210201_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='skilldata',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
