# Generated by Django 3.1.4 on 2021-02-11 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0010_skilldata_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('start', models.DateTimeField(blank=True)),
                ('end', models.DateTimeField(blank=True)),
                ('resume', models.CharField(choices=[('S', 'Sumary'), ('E', 'Education'), ('X', 'Experience')], max_length=12)),
                ('company', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='aboutdata',
            name='languages',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='DetailsData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(max_length=300)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='mainApp.resumedata')),
            ],
        ),
    ]
