# Generated by Django 3.1.4 on 2021-02-11 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0011_auto_20210211_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumedata',
            name='location',
            field=models.CharField(default='Alhama', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resumedata',
            name='end',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='resumedata',
            name='start',
            field=models.DateField(blank=True),
        ),
    ]
