# Generated by Django 3.1.4 on 2021-02-15 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0012_auto_20210211_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumedata',
            name='mainText',
            field=models.TextField(blank=True),
        ),
    ]
