# Generated by Django 3.1.4 on 2021-02-15 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0013_resumedata_maintext'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumedata',
            name='language',
            field=models.CharField(choices=[('E', 'English'), ('S', 'Spanish')], default='E', max_length=7),
        ),
        migrations.AlterField(
            model_name='resumedata',
            name='company',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='resumedata',
            name='end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resumedata',
            name='location',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='resumedata',
            name='resume',
            field=models.CharField(choices=[('S', 'Sumary'), ('M', 'Main'), ('E', 'Education'), ('X', 'Experience')], max_length=12),
        ),
        migrations.AlterField(
            model_name='resumedata',
            name='start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
